# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  dockerId: lixzhang
  imageName: azure-ci-cd
  
steps:
- script: |
    echo "username: $(dockerId)"
    echo "userpw: $(pswd)"
    # docker build -t $(dockerId)/$(imageName) .
    # docker login -u $(dockerId) -p $(pswd)
    # docker push $(dockerId)/$(imageName)
  env:
    pswd: $(dockerPassword) 
